Controllers/Api/MoviesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using Vidly.DTOs;

namespace Vidly.Controllers.Api
{
    [Route("api/movies")]
    [ApiController]
    [Authorize]
    public class MoviesController : ControllerBase
    {
        private ApplicationDbContext _context;
        private IMapper _mapper;
        public MoviesController(IConfiguration configuration, IMapper mapper)
        {
            _context = new ApplicationDbContext(new DbContextOptions<ApplicationDbContext>(), configuration);
            _mapper = mapper;
        }
        //GET /api/movies
        public IEnumerable<MovieDTO> GetMovies(string query = null)
        {
            var moviesQuery = _context.Movies
                .Include(m => m.Genre).Where(m => m.NumberAvailable > 0);
            if (!String.IsNullOrEmpty(query))
            {
                moviesQuery = moviesQuery.Where(c => c.Name.Contains(query));
            }
            return moviesQuery
                .ToList()
                .Select(_mapper.Map<Movie, MovieDTO>);
        }

        //GET /api/movies
        [HttpGet("{id}")]
        public ActionResult<MovieDTO> GetMovie(int id)
        {
            var movie = _context.Movies.Include(m => m.Genre).SingleOrDefault(m => m.Id == id);
            if (movie == null) return NotFound();

            return Ok(_mapper.Map<Movie, MovieDTO>(movie));
        }

        // POST /api/movies
        [HttpPost]
        public ActionResult<MovieDTO> CreateMovie(MovieDTO movieDTO)
        {
            if (!ModelState.IsValid) return BadRequest();
            var movie = _mapper.Map<MovieDTO, Movie>(movieDTO);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDTO.Id = movie.Id; 
            return Created(new Uri(Request.GetDisplayUrl() + "/" + movie.Id), movieDTO);
        }

        // PUT /api/movie/1
        [HttpPut]
        public void UpdateMovie(int id, MovieDTO movieDTO) {
            if (!ModelState.IsValid) throw new BadHttpRequestException("Invalid entry");

            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null) throw new BadHttpRequestException("Movie not found");

            _mapper.Map(movieDTO, movieInDb);
            _context.SaveChanges();
        }

        // DELETE /api/movie/1
        [HttpDelete("{id}")]
        public void DeleteMovie(int id)
        {
            if (!ModelState.IsValid) throw new BadHttpRequestException("Invalid entry");

            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null) throw new BadHttpRequestException("Movie not found");

            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
        }

    }
}

Controllers/RentalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Vidly.Controllers
{
    [Authorize]
    public class RentalsController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Vidly
    </div>
</footer>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vidly.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/forms.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/data-tables/css/dataTables.bootstrap5.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/typeahead.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" asp-append-version="true" />


</head> 
<body>
    <partial name="_Navbar" />;
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bloodhound/bloodhound.min.js"></script>
    <script src="~/lib/bootbox/bootbox.all.min.js"></script>
    <script src="~/lib/data-tables/js/jquery.dataTables.js"></script>
    <script src="~/lib/data-tables/js/dataTables.bootstrap5.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/typeahead.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_Footer" />
</body>
</html>

Views/Shared/_Navbar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vidly</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="New">New Rental</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header>